cursor #91cef5
cursor_text_color #00344b

foreground            #dfe3e7
background            #0f1417
selection_foreground  #20333e
selection_background  #b6c9d8
url_color             #91cef5

color0   #0f1417
color1   #ff729e
color2   #7af589
color3   #fff672
color4   #76bce8
color5   #004c6b
color6   #91cef5
color7   #effaff
color8   #3d4346
color9   #ff9fbd
color10  #a5ffb0
color11  #fff9a5
color12  #a6dcff
color13  #b6e2ff
color14  #d0ecff
color15  #f8fdff
