# ----------------------------------------------------- 
# Environment Variables
# ----------------------------------------------------- 

env = WLR_NO_HARDWARE_CURSORS, 1
env = WLR_RENDERER_ALLOW_SOFTWARE, 1
env = WLR_NO_HARDWARE_CURSORS, 1

env = GDK_BACKEND, wayland, x11, *

env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt5ct

env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

env = GTK_THEME, Adwaita:dark

env = XCURSOR_THEME, Bibata-Modern-Ice
env = XCURSOR_SIZE, 22
